"""agregar sitio_config para foto principal

Revision ID: 605a0c7e99b0
Revises: ec84e28c6a4d
Create Date: 2026-07-22 20:23:33.660892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '605a0c7e99b0'
down_revision: Union[str, None] = 'ec84e28c6a4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sitio_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_image_url', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sitio_config')
    # ### end Alembic commands ###
