"""esquema normalizado: categorias, zonas, trabajos, trabajo_imagenes

Revision ID: ec84e28c6a4d
Revises: 
Create Date: 2026-07-22 19:28:56.099126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ec84e28c6a4d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('zonas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('trabajos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('zona_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('antes_despues', 'foto', name='tipotrabajo'), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('publicado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['zona_id'], ['zonas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trabajo_imagenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trabajo_id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.Enum('antes', 'despues', 'foto', name='rolimagen'), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trabajo_id'], ['trabajos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trabajo_id', 'rol', name='uq_trabajo_imagen_rol')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trabajo_imagenes')
    op.drop_table('trabajos')
    op.drop_table('zonas')
    op.drop_table('categorias')
    # ### end Alembic commands ###
